SET_ROM_BANK := $2100
SET_RAM_BANK := $4000

wCurrentBank := $DBAF
wOAMBuffer := $C000
wRupeeCountHigh := $DB5D
wRupeeCountLow := $DB5E

rLCDC:= $FF40
rSTAT:= $FF41
rSCY := $FF42
rSCX := $FF43
rLY  := $FF44
rLYC := $FF45
rVBK := $FF4F
rWY  := $FF4A
rWX  := $FF4B
rIF  := $FF0F
rIE  := $FFFF
rBCPS:= $FF68
rBGPD:= $FF69
rOCPS:= $FF6A
rOBPD:= $FF6B

hPlayerGfxX := $FF83
hEnemyGfxX := $FF84
ENEMY_GFX_X_START := 7 + 160 - 1
ENEMY_GFX_X_END := 7 + 160 - 65

hLinkPositionX := $FF98
hLinkPositionY := $FF99
hLinkDirection := $FF9E
hTMP0 := $FFD7
hTMP1 := $FFD8
hTMP2 := $FFD9
hTMP3 := $FFDA
hTMP4 := $FFDB
hTMP5 := $FFDC
hTMP6 := $FFDD
hTMP7 := $FFDE
hTMP8 := $FFDF
hTMP9 := $FFE0
hTMPA := $FFE1
hTMPB := $FFE2
hTMPC := $FFE3
hTMPD := $FFE4
hTMPE := $FFE5
hTMPF := $FFE6
hFrameCounter := $FFE7
hJoypadState := $FFCB
hJoypadPressed := $FFCC
hJingleSFX := $FFF2
hWaveSFX := $FFF3
hNoiseSFX := $FFF4

J_RIGHT  := $01
J_LEFT   := $02
J_UP     := $04
J_DOWN   := $08
J_A      := $10
J_B      := $20
J_SELECT := $40
J_START  := $80

J_BIT_RIGHT  := 0
J_BIT_LEFT   := 1
J_BIT_UP     := 2
J_BIT_DOWN   := 3
J_BIT_A      := 4
J_BIT_B      := 5
J_BIT_SELECT := 6
J_BIT_START  := 7

; Functions from bank0
GetRandomByte := $280D

#MACRO farcall
    ld   a, BANK(\1)
    ld   hl, \1
    call do_farcall
#END
#MACRO farcallX
    push af
    ld   a, BANK(\1)
    ld   [do_farcallX.bankLoadInstr + 1], a
    ld   a, LOW(\1)
    ld   [do_farcallX.callInstr + 1], a
    ld   a, HIGH(\1)
    ld   [do_farcallX.callInstr + 2], a
    pop  af
    call do_farcallX
#END
#MACRO farcallXY ; Call X with bank Y active
    push af
    ld   a, \2
    ld   [do_farcallX.bankLoadInstr + 1], a
    ld   a, LOW(\1)
    ld   [do_farcallX.callInstr + 1], a
    ld   a, HIGH(\1)
    ld   [do_farcallX.callInstr + 2], a
    pop  af
    call do_farcallX
#END
#MACRO WAIT_STAT
    ldh  a, [$FF41]
    and  $02
    jr   nz, $FA
#END
#MACRO PUSHV
    ld   hl, \1
    push hl
#END
#MACRO ldhl_add_a
    ld   h, HIGH(\1)
    add  a, LOW(\1)
    ld   l, a
#END
#MACRO ldde_add_a
    ld   d, HIGH(\1)
    add  a, LOW(\1)
    ld   e, a
#END
#MACRO ld16_bc_hl
    ld   b, h
    ld   c, l
#END
#MACRO ld16_bc_de
    ld   b, d
    ld   c, e
#END
#MACRO ld16_de_hl
    ld   d, h
    ld   e, l
#END
#MACRO ld16_de_bc
    ld   d, b
    ld   e, c
#END
#MACRO ld16_hl_bc
    ld   h, b
    ld   l, c
#END
#MACRO ld16_hl_de
    ld   h, d
    ld   l, e
#END
#MACRO DRAW_TEXT_DARK
    ld   de, \3
    ld   hl, $9800 + $20 * (\2) + (\1)
    call drawTextDark
#END
#MACRO DRAW_TEXT_LIGHT
    ld   de, \3
    ld   hl, $9800 + $20 * (\2) + (\1)
    call drawTextLight
#END
#MACRO enumStart
    __ENUM_VALUE := 0
#END
#MACRO enum
    \1 := __ENUM_VALUE
    __ENUM_VALUE := __ENUM_VALUE + 1
#END

; Stat table constants
STAT_TYPE_OFFSET := 5
STAT_CATCH_OFFSET := STAT_TYPE_OFFSET + 2
STAT_EXP_OFFSET := STAT_CATCH_OFFSET + 1
STAT_FRONT_GFX_OFFSET := STAT_EXP_OFFSET + 1
STAT_BACK_GFX_OFFSET := STAT_FRONT_GFX_OFFSET + 6
STAT_MOVES_OFFSET := STAT_BACK_GFX_OFFSET + 6
STAT_MOVE_LEARN_OFFSET := STAT_MOVES_OFFSET + 4
STAT_NAME_OFFSET := STAT_MOVE_LEARN_OFFSET + 2
STAT_ENTRY_SIZE := STAT_NAME_OFFSET + 8
; Move table constants
MOVE_EFFECT_OFFSET := 2
MOVE_POWER_OFFSET := MOVE_EFFECT_OFFSET + 1
MOVE_TYPE_OFFSET := MOVE_POWER_OFFSET + 1
MOVE_ACCURACY_OFFSET := MOVE_TYPE_OFFSET + 1
MOVE_PP_OFFSET := MOVE_ACCURACY_OFFSET + 1
MOVE_ENTRY_SIZE := 7

enumStart
enum NO_ADDITIONAL_EFFECT
enum ACCURACY_DOWN1_EFFECT
enum ATTACK_DOWN1_EFFECT
enum ATTACK_DOWN_SIDE_EFFECT
enum ATTACK_TWICE_EFFECT
enum ATTACK_UP1_EFFECT
enum ATTACK_UP2_EFFECT
enum BIDE_EFFECT
enum BURN_SIDE_EFFECT1
enum BURN_SIDE_EFFECT2
enum CHARGE_EFFECT
enum CONFUSION_EFFECT
enum CONFUSION_SIDE_EFFECT
enum CONVERSION_EFFECT
enum DEFENSE_DOWN1_EFFECT
enum DEFENSE_DOWN2_EFFECT
enum DEFENSE_DOWN_SIDE_EFFECT
enum DEFENSE_UP1_EFFECT
enum DEFENSE_UP2_EFFECT
enum DISABLE_EFFECT
enum DRAIN_HP_EFFECT
enum DREAM_EATER_EFFECT
enum EVASION_UP1_EFFECT
enum EXPLODE_EFFECT
enum FLINCH_SIDE_EFFECT1
enum FLINCH_SIDE_EFFECT2
enum FLY_EFFECT
enum FOCUS_ENERGY_EFFECT
enum FREEZE_SIDE_EFFECT
enum HAZE_EFFECT
enum HEAL_EFFECT
enum HYPER_BEAM_EFFECT
enum JUMP_KICK_EFFECT
enum LEECH_SEED_EFFECT
enum LIGHT_SCREEN_EFFECT
enum METRONOME_EFFECT
enum MIMIC_EFFECT
enum MIRROR_MOVE_EFFECT
enum MIST_EFFECT
enum OHKO_EFFECT
enum PARALYZE_EFFECT
enum PARALYZE_SIDE_EFFECT1
enum PARALYZE_SIDE_EFFECT2
enum PAY_DAY_EFFECT
enum POISON_EFFECT
enum POISON_SIDE_EFFECT1
enum POISON_SIDE_EFFECT2
enum RAGE_EFFECT
enum RECOIL_EFFECT
enum REFLECT_EFFECT
enum SLEEP_EFFECT
enum SPECIAL_DAMAGE_EFFECT
enum SPECIAL_DOWN_SIDE_EFFECT
enum SPECIAL_UP1_EFFECT
enum SPECIAL_UP2_EFFECT
enum SPEED_DOWN1_EFFECT
enum SPEED_DOWN_SIDE_EFFECT
enum SPEED_UP2_EFFECT
enum SPLASH_EFFECT
enum SUBSTITUTE_EFFECT
enum SUPER_FANG_EFFECT
enum SWIFT_EFFECT
enum SWITCH_AND_TELEPORT_EFFECT
enum THRASH_PETAL_DANCE_EFFECT
enum TRANSFORM_EFFECT
enum TRAPPING_EFFECT
enum TWINEEDLE_EFFECT
enum TWO_TO_FIVE_ATTACKS_EFFECT

; Move indexes
MOVE_POUND := 1
MOVE_KARATE_CHOP := 2
MOVE_DOUBLESLAP := 3
MOVE_COMET_PUNCH := 4
MOVE_MEGA_PUNCH := 5
MOVE_PAY_DAY := 6
MOVE_FIRE_PUNCH := 7
MOVE_ICE_PUNCH := 8
MOVE_THUNDERPUNCH := 9
MOVE_SCRATCH := 10
MOVE_VICEGRIP := 11
MOVE_GUILLOTINE := 12
MOVE_RAZOR_WIND := 13
MOVE_SWORDS_DANCE := 14
MOVE_CUT := 15
MOVE_GUST := 16
MOVE_WING_ATTACK := 17
MOVE_WHIRLWIND := 18
MOVE_FLY := 19
MOVE_BIND := 20
MOVE_SLAM := 21
MOVE_VINE_WHIP := 22
MOVE_STOMP := 23
MOVE_DOUBLE_KICK := 24
MOVE_MEGA_KICK := 25
MOVE_JUMP_KICK := 26
MOVE_ROLLING_KICK := 27
MOVE_SAND_ATTACK := 28
MOVE_HEADBUTT := 29
MOVE_HORN_ATTACK := 30
MOVE_FURY_ATTACK := 31
MOVE_HORN_DRILL := 32
MOVE_TACKLE := 33
MOVE_BODY_SLAM := 34
MOVE_WRAP := 35
MOVE_TAKE_DOWN := 36
MOVE_THRASH := 37
MOVE_DOUBLE_EDGE := 38
MOVE_TAIL_WHIP := 39
MOVE_POISON_STING := 40
MOVE_TWINEEDLE := 41
MOVE_PIN_MISSILE := 42
MOVE_LEER := 43
MOVE_BITE := 44
MOVE_GROWL := 45
MOVE_ROAR := 46
MOVE_SING := 47
MOVE_SUPERSONIC := 48
MOVE_SONICBOOM := 49
MOVE_DISABLE := 50
MOVE_ACID := 51
MOVE_EMBER := 52
MOVE_FLAMETHROWER := 53
MOVE_MIST := 54
MOVE_WATER_GUN := 55
MOVE_HYDRO_PUMP := 56
MOVE_SURF := 57
MOVE_ICE_BEAM := 58
MOVE_BLIZZARD := 59
MOVE_PSYBEAM := 60
MOVE_BUBBLEBEAM := 61
MOVE_AURORA_BEAM := 62
MOVE_HYPER_BEAM := 63
MOVE_PECK := 64
MOVE_DRILL_PECK := 65
MOVE_SUBMISSION := 66
MOVE_LOW_KICK := 67
MOVE_COUNTER := 68
MOVE_SEISMIC_TOSS := 69
MOVE_STRENGTH := 70
MOVE_ABSORB := 71
MOVE_MEGA_DRAIN := 72
MOVE_LEECH_SEED := 73
MOVE_GROWTH := 74
MOVE_RAZOR_LEAF := 75
MOVE_SOLARBEAM := 76
MOVE_POISONPOWDER := 77
MOVE_STUN_SPORE := 78
MOVE_SLEEP_POWDER := 79
MOVE_PETAL_DANCE := 80
MOVE_STRING_SHOT := 81
MOVE_DRAGON_RAGE := 82
MOVE_FIRE_SPIN := 83
MOVE_THUNDERSHOCK := 84
MOVE_THUNDERBOLT := 85
MOVE_THUNDER_WAVE := 86
MOVE_THUNDER := 87
MOVE_ROCK_THROW := 88
MOVE_EARTHQUAKE := 89
MOVE_FISSURE := 90
MOVE_DIG := 91
MOVE_TOXIC := 92
MOVE_CONFUSION := 93
MOVE_PSYCHIC_M := 94
MOVE_HYPNOSIS := 95
MOVE_MEDITATE := 96
MOVE_AGILITY := 97
MOVE_QUICK_ATTACK := 98
MOVE_RAGE := 99
MOVE_TELEPORT := 100
MOVE_NIGHT_SHADE := 101
MOVE_MIMIC := 102
MOVE_SCREECH := 103
MOVE_DOUBLE_TEAM := 104
MOVE_RECOVER := 105
MOVE_HARDEN := 106
MOVE_MINIMIZE := 107
MOVE_SMOKESCREEN := 108
MOVE_CONFUSE_RAY := 109
MOVE_WITHDRAW := 110
MOVE_DEFENSE_CURL := 111
MOVE_BARRIER := 112
MOVE_LIGHT_SCREEN := 113
MOVE_HAZE := 114
MOVE_REFLECT := 115
MOVE_FOCUS_ENERGY := 116
MOVE_BIDE := 117
MOVE_METRONOME := 118
MOVE_MIRROR_MOVE := 119
MOVE_SELFDESTRUCT := 120
MOVE_EGG_BOMB := 121
MOVE_LICK := 122
MOVE_SMOG := 123
MOVE_SLUDGE := 124
MOVE_BONE_CLUB := 125
MOVE_FIRE_BLAST := 126
MOVE_WATERFALL := 127
MOVE_CLAMP := 128
MOVE_SWIFT := 129
MOVE_SKULL_BASH := 130
MOVE_SPIKE_CANNON := 131
MOVE_CONSTRICT := 132
MOVE_AMNESIA := 133
MOVE_KINESIS := 134
MOVE_SOFTBOILED := 135
MOVE_HI_JUMP_KICK := 136
MOVE_GLARE := 137
MOVE_DREAM_EATER := 138
MOVE_POISON_GAS := 139
MOVE_BARRAGE := 140
MOVE_LEECH_LIFE := 141
MOVE_LOVELY_KISS := 142
MOVE_SKY_ATTACK := 143
MOVE_TRANSFORM := 144
MOVE_BUBBLE := 145
MOVE_DIZZY_PUNCH := 146
MOVE_SPORE := 147
MOVE_FLASH := 148
MOVE_PSYWAVE := 149
MOVE_SPLASH := 150
MOVE_ACID_ARMOR := 151
MOVE_CRABHAMMER := 152
MOVE_EXPLOSION := 153
MOVE_FURY_SWIPES := 154
MOVE_BONEMERANG := 155
MOVE_REST := 156
MOVE_ROCK_SLIDE := 157
MOVE_HYPER_FANG := 158
MOVE_SHARPEN := 159
MOVE_CONVERSION := 160
MOVE_TRI_ATTACK := 161
MOVE_SUPER_FANG := 162
MOVE_SLASH := 163
MOVE_SUBSTITUTE := 164
MOVE_STRUGGLE := 165

enumStart
enum MON_OCTOROCK
enum MON_MOBLIN
enum MON_PIGWARRIOR
enum MON_DARKNUT
enum MON_SHROUDED_STALFOS
enum MON_TEKTITE
enum MON_LEEVER
enum MON_ARMOS_STATUE
enum MON_GHINI
enum MON_GIANT_GHINI
enum MON_MOBLIN_SWORD
enum MON_PIGWARRIOR_SWORD
enum MON_DARKNUT_SWORD
enum MON_SHROUDED_STALFOS_SWORD
enum MON_ANTI_FAIRY
enum MON_SPARK
enum MON_POLS_VOICE
enum MON_KEESE
enum MON_STALFOS
enum MON_GREEN_ZOL
enum MON_RED_ZOL
enum MON_GEL
enum MON_GIBDO
enum MON_HARDHAT_BEETLE
enum MON_WIZROBE
enum MON_LIKE_LIKE
enum MON_IRON_MASK
enum MON_MIMIC
enum MON_MINI_MOLDORM
enum MON_SPIKED_BEETLE
enum MON_BOO_BUDDY
enum MON_BALL_AND_CHAIN
enum MON_BOMBITE
enum MON_PAIRODD
enum MON_MASKED_MIMIC
enum MON_CROW
enum MON_GIANT_GOPONGA_FLOWER
enum MON_GOPONGA_FLOWER
enum MON_THREE_OF_A_KIND
enum MON_ANTI_KIRBY
enum MON_MAD_BOMBER
enum MON_HORSE_PIECE
enum MON_WATER_TEKTITE
enum MON_FLYING_TILE
enum MON_STAR
enum MON_GOOMBA
enum MON_PEAHAT
enum MON_SNAKE
enum MON_PIRANHA_PLANT
enum MON_BLOOPER
enum MON_CHEEP_CHEEP
enum MON_WINGED_OCTOROK
enum MON_PINCER
enum MON_BEETLE
enum MON_BUZZ_BLOB
enum MON_CUKEMAN
enum MON_BOMBER
enum MON_BUSH_CRAWLER
enum MON_VIRE
enum MON_ZOMBIE
enum MON_URCHIN
enum MON_SAND_CRAB
enum MON_ZORA
enum MON_FISH
enum MON_THWIMP
enum MON_THWOMP
enum MON_GIANT_THWOMP
enum MON_PODOBOO
enum MON_MONKEY
enum MON_POKEY
enum MON_RED_ORB
enum MON_GREEN_ORB
enum MON_BLUE_ORB
enum MON_RED_CAMO
enum MON_GREEN_CAMO
enum MON_BLUE_CAMO
enum MON_HOPPER

enum MON_GHOMA
enum MON_MASTER_STALFOS
enum MON_DODONGO_SNAKE
enum MON_TURTLE_ROCK_HEAD
enum MON_ROLLING_BONES
enum MON_DESERT_LANMOLA
enum MON_ARMOS_KNIGHT
enum MON_HINOX
enum MON_CUE_BALL
enum MON_SMASHER
enum MON_GRIM_CREEPER
enum MON_BLAINO
enum MON_MOBLIN_KING
enum MON_AVALAUNCH
enum MON_GIANT_BUZZ_BLOB

enum MON_MOLDORM
enum MON_FACADE
enum MON_SLIME_EYE
enum MON_GENIE
enum MON_SLIME_EEL
enum MON_HOT_HEAD
enum MON_EVIL_EAGLE
enum MON_ANGLER_FISH
enum MON_HARDHIT_BEETLE


enumStart
enum NORMAL
enum FIGHTING
enum FLYING
enum POISON
enum GROUND
enum ROCK
enum BUG
enum GHOST
enum FIRE
enum WATER
enum GRASS
enum ELECTRIC
enum PSYCHIC
enum ICE
enum DRAGON

enumStart
enum ITEM_NONE
enum ITEM_POTION
enum ITEM_BAIT